DROP TABLE IF EXISTS `fwlink`;
DROP TABLE IF EXISTS `user`;

CREATE TABLE `fwlink` (
    `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `url` TEXT NOT NULL
) AUTO_INCREMENT 1000000000;

CREATE TABLE `user` (
    `username` VARCHAR(16) PRIMARY KEY,
    `password` VARCHAR(32) NOT NULL
);